global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Hello World приложение
  - job_name: 'hello-world'
    static_configs:
      - targets: ['hello-world:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Nginx метрики
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    
  # Redis метрики
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  # Системные метрики
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Правила алертов
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Примеры правил мониторинга
# rule_files:
#   - "alert_rules.yml"